In [1]:
import os
import numpy as np
from pathlib import Path
import torch
from torch import nn


In [2]:
print(os.getcwd())
os.chdir("..")
print(os.getcwd())

bindata = {}
for fp in sorted(Path("data/ManipNetBIN").iterdir()):
    # print(fp)
    bindata[fp.stem] = np.fromfile(fp, dtype=np.float32)
for k, v in bindata.items():
    print(k, v.shape)

os.chdir("data/ManipNetBIN")
print(os.getcwd())
# num = np.fromfile('Decoder_b0.bin')
# print(num)

/workspace/rendering/network
/workspace/rendering
Decoder_b0 (214,)
Decoder_w0 (328704,)
DenseRes0_b0 (1536,)
DenseRes0_w0 (2359296,)
DenseRes1_b0 (1536,)
DenseRes1_w0 (2359296,)
DenseRes2_b0 (1536,)
DenseRes2_w0 (2359296,)
DenseRes3_b0 (1536,)
DenseRes3_w0 (2359296,)
Encoder0_b0 (512,)
Encoder0_w0 (98304,)
Encoder1_b0 (512,)
Encoder1_w0 (172032,)
Encoder2_b0 (512,)
Encoder2_w0 (932864,)
Xmean (2350,)
Xstd (2350,)
Ymean (214,)
Ystd (214,)
/workspace/rendering/data/ManipNetBIN


In [3]:
import torch.nn.functional as F

class ResBlock(nn.Module):
    def __init__(self, in_vec, out_vec):
        super(ResBlock, self).__init__()
        self.FC0= nn.Linear(in_vec, out_vec)
        self.FC1 = nn.Linear(in_vec, out_vec)
        # self.relu = nn.ReLU()

        # self.sequence = nn.Sequential(
        #     [
        #         nn.Linear(),
        #         nn.ReLU(),
        #     ]
        # )

    def __call__(self, H_zero):
        # H_zero = nn.ReLU(H_zero)
        H_zero_ = F.relu(H_zero)
        H_one = self.FC0(H_zero_) + H_zero_
        # H_one  = nn.ReLU(H_one)
        H_one_ = F.relu(H_one)
        H_two = self.FC1(H_one_) + H_one_ + H_zero_
        return H_two


In [4]:
# 訓練に際して、可能であればGPU（cuda）を設定します。GPUが搭載されていない場合はCPUを使用します
device = "cuda:0" if torch.cuda.is_available() else "cpu"
print("Using {} device".format(device))

# modelを定義します
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.Encoder0= nn.Linear(192, 512)
        self.Encoder1 = nn.Linear(336, 512)
        self.Encoder2 = nn.Linear(1822, 512)
        self.DenseRes0 = ResBlock(1536, 1536)
        self.DenseRes1 = ResBlock(1536, 1536)
        self.Decoder = nn.Linear(1536, 214)

    def forward(self, pose, traj, sensor):
        pose_ = self.Encoder0(pose)
        traj_ = self.Encoder1(traj)
        sensor_ = self.Encoder2(sensor)
        out = torch.cat([pose_, traj_, sensor_], dim=-1)
        out = self.DenseRes0(out)
        out = self.DenseRes1(out)
        out = self.Decoder(out)
        return out

model = NeuralNetwork().to(device)
print(device)
print(model)
# model()
# print(model.device)
# for param in model.Encoder1.parameters():
#     print("encoder", param.shape)
pose, traj, sensor = torch.zeros([1,192]).to(device), torch.zeros([1,336]).to(device), torch.zeros([1,1822]).to(device)
y = model(pose, traj, sensor)

Using cuda:0 device
cuda:0
NeuralNetwork(
  (Encoder0): Linear(in_features=192, out_features=512, bias=True)
  (Encoder1): Linear(in_features=336, out_features=512, bias=True)
  (Encoder2): Linear(in_features=1822, out_features=512, bias=True)
  (DenseRes0): ResBlock(
    (FC0): Linear(in_features=1536, out_features=1536, bias=True)
    (FC1): Linear(in_features=1536, out_features=1536, bias=True)
  )
  (DenseRes1): ResBlock(
    (FC0): Linear(in_features=1536, out_features=1536, bias=True)
    (FC1): Linear(in_features=1536, out_features=1536, bias=True)
  )
  (Decoder): Linear(in_features=1536, out_features=214, bias=True)
)


In [5]:
for name, param in model.named_parameters():
    print(name, param.shape)

Encoder0.weight torch.Size([512, 192])
Encoder0.bias torch.Size([512])
Encoder1.weight torch.Size([512, 336])
Encoder1.bias torch.Size([512])
Encoder2.weight torch.Size([512, 1822])
Encoder2.bias torch.Size([512])
DenseRes0.FC0.weight torch.Size([1536, 1536])
DenseRes0.FC0.bias torch.Size([1536])
DenseRes0.FC1.weight torch.Size([1536, 1536])
DenseRes0.FC1.bias torch.Size([1536])
DenseRes1.FC0.weight torch.Size([1536, 1536])
DenseRes1.FC0.bias torch.Size([1536])
DenseRes1.FC1.weight torch.Size([1536, 1536])
DenseRes1.FC1.bias torch.Size([1536])
Decoder.weight torch.Size([214, 1536])
Decoder.bias torch.Size([214])


In [6]:
for k, v in bindata.items():
    print(k, v.shape)

Decoder_b0 (214,)
Decoder_w0 (328704,)
DenseRes0_b0 (1536,)
DenseRes0_w0 (2359296,)
DenseRes1_b0 (1536,)
DenseRes1_w0 (2359296,)
DenseRes2_b0 (1536,)
DenseRes2_w0 (2359296,)
DenseRes3_b0 (1536,)
DenseRes3_w0 (2359296,)
Encoder0_b0 (512,)
Encoder0_w0 (98304,)
Encoder1_b0 (512,)
Encoder1_w0 (172032,)
Encoder2_b0 (512,)
Encoder2_w0 (932864,)
Xmean (2350,)
Xstd (2350,)
Ymean (214,)
Ystd (214,)


In [7]:
netlist = ["Decoder"]
net_name_list = []
# for i in range(4):
#     netlist.append("DenseRes" + str(i))
for i in range(3):
    netlist.append("Encoder" + str(i))
print(netlist)
for name in netlist:
    net_name_list.append([name + ".weight", name + "_w0"])
    net_name_list.append([name + ".bias", name + "_b0"])

shape_list = [[214, 1536], [214], [512, 192], [512], [512, 336], [512], [512, 1822], [512]]
for i in range(len(net_name_list)):
    net_name_list[i].append(shape_list[i])
print(net_name_list)

dense_weight_list = []
dense_bias_list = []
for i in range(2):
    for j in range(2):
        dense_weight_list.append(["DenseRes" + str(i) + ".FC" + str(j) + ".weight", "DenseRes" + str(2 * i + j) + "_w0"])
        dense_bias_list.append(["DenseRes" + str(i) + ".FC" + str(j) + ".bias", "DenseRes" + str(2 * i + j) + "_b0"])


['Decoder', 'Encoder0', 'Encoder1', 'Encoder2']
[['Decoder.weight', 'Decoder_w0', [214, 1536]], ['Decoder.bias', 'Decoder_b0', [214]], ['Encoder0.weight', 'Encoder0_w0', [512, 192]], ['Encoder0.bias', 'Encoder0_b0', [512]], ['Encoder1.weight', 'Encoder1_w0', [512, 336]], ['Encoder1.bias', 'Encoder1_b0', [512]], ['Encoder2.weight', 'Encoder2_w0', [512, 1822]], ['Encoder2.bias', 'Encoder2_b0', [512]]]


# 読み込み

In [8]:
getbinname = {
    "Decoder.weight": "Decoder_w0",
    "Decoder.bias": "Decoder_b0",
    "Encoder0.weight": "Encoder0_w0",
    "Encoder0.bias": "Encoder0_b0",
    "Encoder1.weight": "Encoder1_w0",
    "Encoder1.bias": "Encoder1_b0",
    "Encoder2.weight": "Encoder2_w0",
    "Encoder2.bias": "Encoder2_b0",
    "DenseRes0.FC0.weight": "DenseRes0_w0",
    "DenseRes0.FC0.bias": "DenseRes0_b0",
    "DenseRes0.FC1.weight": "DenseRes1_w0",
    "DenseRes0.FC1.bias": "DenseRes1_b0",
    "DenseRes1.FC0.weight": "DenseRes2_w0",
    "DenseRes1.FC0.bias": "DenseRes2_b0",
    "DenseRes1.FC1.weight": "DenseRes3_w0",
    "DenseRes1.FC1.bias": "DenseRes3_b0",

}
# print(os.getcwd())
#
with torch.no_grad():
    for name, param in model.named_parameters():
        print(name, getbinname[name])
        # fp = f"data/ManipNetBIN/{getbinname[name]}.bin"
        fp = f"{getbinname[name]}.bin"
        savednp = np.fromfile(fp, dtype=np.float32)
        print(savednp.shape)
        # savedweight = torch.from_numpy(savednp)
        shape_ = param.shape
        print(shape_)

        # print(shape_, shape_[0], shape_[1])
        param.copy_(torch.from_numpy(savednp.reshape(shape_, order="C"))) 
        # param.copy_(torch.from_numpy(savednp.reshape(shape_, order="F"))) 
        print(param)
        print(savednp)


Encoder0.weight Encoder0_w0
(98304,)
torch.Size([512, 192])
Parameter containing:
tensor([[-0.0751, -0.0893,  0.0815,  ..., -0.0023,  0.0108,  0.0553],
        [-0.0455,  0.0524, -0.0306,  ..., -0.0354, -0.0475, -0.0086],
        [-0.0329,  0.0703, -0.0476,  ...,  0.0040,  0.0093, -0.0899],
        ...,
        [ 0.0060,  0.0643, -0.0282,  ...,  0.0184,  0.0319, -0.0253],
        [-0.0182,  0.0615,  0.0271,  ...,  0.0675, -0.0561, -0.0581],
        [-0.0358,  0.0303,  0.0649,  ..., -0.0089,  0.0761, -0.2177]],
       device='cuda:0', requires_grad=True)
[-0.07508604 -0.08928403  0.08154082 ... -0.00894041  0.07614809
 -0.21765612]
Encoder0.bias Encoder0_b0
(512,)
torch.Size([512])
Parameter containing:
tensor([-0.1640, -0.3014, -0.1578, -0.0544, -0.2442, -0.4230, -0.0730, -0.1455,
        -0.1958, -0.2338, -0.1662, -0.1184, -0.1595, -0.1054, -0.2449, -0.2744,
         0.3854, -0.2818,  0.5248, -0.0677, -0.1090, -0.1178, -0.2102,  0.2377,
         0.4789,  0.1886, -0.2035, -0.2202, -0.3

In [9]:
with torch.no_grad():
    for name, param in model.named_parameters():
        print(name)
        for k, v in bindata.items():
            for i in range(len(net_name_list)):
                # print(net_name_list[i][0], name)
                if name == net_name_list[i][0] and k == net_name_list[i][1]:
                    print(param.shape, name, k)
                    rephape_weight = torch.reshape(torch.from_numpy(bindata[net_name_list[i][1]]), net_name_list[i][2])
                    param.copy_(rephape_weight)
        for i in range(len(dense_weight_list)):
            if name == dense_weight_list[i][0]:
                param.copy_(torch.reshape(torch.from_numpy(bindata[dense_weight_list[i][1]]), [1536, 1536]))
            if name == dense_bias_list[i][0]:
                param.copy_(torch.reshape(torch.from_numpy(bindata[dense_bias_list[i][1]]), [1536]))


Encoder0.weight
torch.Size([512, 192]) Encoder0.weight Encoder0_w0
Encoder0.bias
torch.Size([512]) Encoder0.bias Encoder0_b0
Encoder1.weight
torch.Size([512, 336]) Encoder1.weight Encoder1_w0
Encoder1.bias
torch.Size([512]) Encoder1.bias Encoder1_b0
Encoder2.weight
torch.Size([512, 1822]) Encoder2.weight Encoder2_w0
Encoder2.bias
torch.Size([512]) Encoder2.bias Encoder2_b0
DenseRes0.FC0.weight
DenseRes0.FC0.bias
DenseRes0.FC1.weight
DenseRes0.FC1.bias
DenseRes1.FC0.weight
DenseRes1.FC0.bias
DenseRes1.FC1.weight
DenseRes1.FC1.bias
Decoder.weight
torch.Size([214, 1536]) Decoder.weight Decoder_w0
Decoder.bias
torch.Size([214]) Decoder.bias Decoder_b0


In [10]:
with torch.no_grad():
    for name, param in model.named_parameters():
        print(name, param)

Encoder0.weight Parameter containing:
tensor([[-0.0751, -0.0893,  0.0815,  ..., -0.0023,  0.0108,  0.0553],
        [-0.0455,  0.0524, -0.0306,  ..., -0.0354, -0.0475, -0.0086],
        [-0.0329,  0.0703, -0.0476,  ...,  0.0040,  0.0093, -0.0899],
        ...,
        [ 0.0060,  0.0643, -0.0282,  ...,  0.0184,  0.0319, -0.0253],
        [-0.0182,  0.0615,  0.0271,  ...,  0.0675, -0.0561, -0.0581],
        [-0.0358,  0.0303,  0.0649,  ..., -0.0089,  0.0761, -0.2177]],
       device='cuda:0', requires_grad=True)
Encoder0.bias 

Parameter containing:
tensor([-0.1640, -0.3014, -0.1578, -0.0544, -0.2442, -0.4230, -0.0730, -0.1455,
        -0.1958, -0.2338, -0.1662, -0.1184, -0.1595, -0.1054, -0.2449, -0.2744,
         0.3854, -0.2818,  0.5248, -0.0677, -0.1090, -0.1178, -0.2102,  0.2377,
         0.4789,  0.1886, -0.2035, -0.2202, -0.3630, -0.1779, -0.1787, -0.0984,
        -0.1555, -0.1249, -0.1549, -0.3549, -0.1839, -0.1523, -0.1989, -0.1677,
        -0.0936, -0.1551, -0.2757, -0.1913, -0.2227, -0.1848, -0.1450, -0.2108,
         0.2748, -0.3838, -0.1906, -0.0878, -0.3309, -0.2950, -0.1489, -0.1433,
        -0.0678, -0.0986, -0.3596, -0.3442, -0.1202, -0.1292, -0.2998, -0.3798,
        -0.5403, -0.2838,  0.3112, -0.2935, -0.3343, -0.2571, -0.0496, -0.1544,
        -0.1000, -0.3391, -0.3416, -0.2133, -0.2621, -0.3774, -0.1920, -0.1826,
        -0.2558, -0.2018, -0.3717,  0.1867, -0.1788, -0.1508, -0.3846, -0.2013,
        -0.1610, -0.1289,  0.4089, -0.1777, -0.3522, -0.1177,  0.5571, -0.3284,
         0.5220, -

In [11]:
# test data
# model.eval()
# 2350 = 192 + 336 + 1822

# x, y = torch.from_numpy(bindata["Xstd"]), torch.from_numpy(bindata["Ystd"])
# with torch.no_grad():
#     pred = model.forward(x[:192], x[192:528], x[528:])
#     # predicted, actual = classes[pred[0].argmax(0)], classes[y]
#     print(f'Predicted: {pred}')
#     print(f"Actual: {y}")
#     print()

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat2 in method wrapper_mm)

In [12]:
Xmean = np.fromfile("Xmean.bin", dtype=np.float32)
Ymean = np.fromfile("Ymean.bin", dtype=np.float32)
print(Xmean.shape, Xmean[-20:])
print(Ymean.shape, Ymean[-20:])

(2350,) [-0.61872  0.44557  0.17121 -0.65208  0.34153  0.36247  0.28213 -0.08111
 -0.28643 -0.33598  0.17554 -0.23346 -0.46493  0.07751 -0.10986 -0.52472
  0.10809  0.13183 -0.62187  0.22497]
(214,) [0.92892 0.77443 0.53388 0.6854  0.53704 0.5237  0.80279 0.66747 0.57714
 0.83595 0.76592 0.66795 0.87527 0.8128  0.73279 0.63066 0.63877 0.80745
 0.79434 0.76837]


In [14]:
# loss_fn = nn.CrossEntropyLoss()
loss_fn = nn.MSELoss()
model.to(device)

def test(bindata, model):
    model.eval()
    test_loss, correct = 0, 0
    with torch.no_grad():
        x, y = torch.from_numpy(bindata["Xmean"]), torch.from_numpy(bindata["Ymean"])
        pose = x[:192].to(device).unsqueeze(0)
        traj = x[192:528].to(device).unsqueeze(0)
        sensor = x[528:].to(device).unsqueeze(0)
        y = y.to(device).unsqueeze(0)
        pred = model(pose, traj, sensor)
        test_loss = loss_fn(pred, y)
    
    torch.set_printoptions(threshold=10_000)
    print(f"Input: {x[:16]}")
    print(f"Actual: {y.squeeze(0)[:16]}")
    print(f'Predicted: {pred.squeeze(0)[:16]}')
    print(f"Loss: {test_loss}")

test(bindata, model)

Input: tensor([ 0.0000,  0.0000,  0.0000, -0.2251,  0.1177, -0.0623, -0.4226,  0.2596,
        -0.1927, -0.7172,  0.3679, -0.3507, -1.0464,  0.4562, -0.4728, -1.0769])
Actual: tensor([ 0.0000,  0.0000,  0.0000, -0.2251,  0.1177, -0.0623, -0.4226,  0.2596,
        -0.1927, -0.7172,  0.3679, -0.3507, -1.0464,  0.4563, -0.4728, -1.0769],
       device='cuda:0')
Predicted: tensor([ 0.0005,  0.0005,  0.0005,  0.0005,  0.0005,  0.0005, -0.1027,  0.0645,
        -0.0620, -0.3811,  0.1370,  0.0357, -0.4754, -0.0834,  0.0494,  0.0005],
       device='cuda:0')
Loss: 0.21744012832641602
